package com.andrefdias.dailynote.util

object Naturezas {
    val listaCompleta = listOf(
        "A 05 - Agressão",
        "A 21 - Encontro de Cadáver",
        "A 22 - Suicídio",
        "A 23 - Tentativa de Suicídio",
        "A 24 - Afogamento em Curso",
        "C 03 - Embriaguez",
        "C 04 - Desinteligência",
        "E 07 - Apoio",
        "L 01 - Veículo",
        "L 03 - Direção de Veículo",
        "L 04 - Congestionamento",
        "L 05 - Infração de Trânsito",
        "L 06 - Interdição de Via Pública",
        "L 07 - Atropelamento",
        "L 08 - Acidente de Tr. C/ Vítima",
        "L 09 - Acidente de Tr. S/ Vítima",
        "L 12 - Acidente de Tr. C/ Moto",
        "M 01 - Oc. c/ Pessoas",
        "M 02 - Choque Elétrico",
        "M 03 - Merg. Salto Água Causa Traum.",
        "M 04 - Inseto Agressivo",
        "M 05 - Overdose",
        "M 06 - Ingestão / Injeção de Substância",
        "M 07 - Intoxic. por Exposição a Gases",
        "M 08 - Lesão por Exposição a Prod. Perig.",
        "M 10 - Desmoronamento",
        "M 11 - Auxílio a Gestante",
        "M 14 - Mal Súbito",
        "M 15 - Queda da Própria",
        "M 15 - Queda de um Nível ao Outro",
        "M 16 - Queimadura",
        "N 01 - Incêndio em Residência",
        "N 01 - Incêndio - Fogo em Mato",
        "N 01 - Incêndio em Veículo",
        "N 01 - Incêndio em Indústria",
        "N 01 - Incêndio em Galpão",
        "N 01 - Incêndio em Fio Energizado",
        "N 02 - Explosão",
        "N 04 - Vazamento",
        "N 08 - Acidente c/ Meio de Transporte",
        "N 10 - Desab. / Desm. / Soterramento",
        "N 12 - Animal Agressivo",
        "N 14 - Inundação / Enchente",
        "N 15 - Queda de Fio Energizado",
        "N 16 - Embarcação em Situação de Risco",
        "N 17 - Odor de Produto Químico",
        "N 21 - Queda de Árvore",
        "N 22 - Risco Iminente / Explosão",
        "N 23 - Situação de Risco",
        "N 24 - Vazamento GLP",
        "N 26 - Animal em Situação de Risco",
        "Z 99 - Ocorrência não Cadastrada",
        "Treinamento Físico",
        "Check-up",
        "M 22 - Emergência Clínica"
    )
}
